### ISSUE TITLE
use mysql storage

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-adapter#168]
[Support for MySQL has been added to edge-core](https://github.com/trustbloc/edge-core/blob/master/pkg/storage/mysql/mysqlstore.go). We should switch to using that instead of the memory storage providers and test.

- [x] edge-core mysql storage #216
- [ ] aries-framework-go mysql storage #321

related: #316

**Comment by rolsonquadras** [comment]
> * [ ]  aries-framework-go mysql storage
> 

Created an issuer for this https://github.com/trustbloc/edge-adapter/issues/321.
