### ISSUE TITLE
Should use authorization terminology

### ISSUE THREAD

**Issue by troyronda** [trustbloc/edge-adapter#188]
I think we should use the more generic authorization terminology rather than "consent". For example, an `AuthorizationCredential` rather than a `ConsentCredential`. In our demonstrations, we happen to be showing a user-consented authorization for a resource.

Similar to [UMA](https://docs.kantarainitiative.org/uma/rec-uma-core.html)

**Comment by rolsonquadras** [comment]
New AuthorizationCredential context is available at https://github.com/trustbloc/context/blob/master/vc/authorization-credential-v1.jsonld
