### ISSUE TITLE
[RP adapter] Configure scope-presentation exchange

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/edge-adapter#234]
part of #232

Currently, we can't configure multiple presentation exchange queries as its hardcoded to one query.

https://github.com/trustbloc/edge-adapter/blob/106c7293da8403fa8221139b87602ed995636fb1/pkg/presentationex/provider.go#L41-L44

**Comment by llorllale** [comment]
@rolsonquadras I started working on this right now

**Comment by llorllale** [comment]
this is blocked by #211: using the framework's new presentation-exchange API requires pulling the fixes made for `verifiable.ParsePresentation()` in hyperledger/aries-framework-go#2052, which requires extensive refactors in tests

**Comment by llorllale** [comment]
Currently blocked until #242 is merged
