### ISSUE TITLE
0.1.4 Release Notes

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-adapter#297]
Initial Release for the RP Adapter and the Issuer Adapter.

## RP Adapter

The Relying Party (RP) Adapter enables standard OpenID Connect flows on top of DIDComm. It exposes a standard OpenID Connect provider service and transparently handles the mechanics of DIDComm on behalf of relying parties.

[Documentation](https://github.com/trustbloc/edge-adapter/blob/master/docs/rp/README.md).

Features:

* OIDC client registration
* OIDC authorization and token endpoints
* Bootstrap DIDComm connections with end-user wallets using the [Credential Handler API polyfill](https://github.com/digitalbazaar/credential-handler-polyfill/blob/master/README.md)
* Transform OAuth2 scopes to a [presentation-exchange proof request](https://identity.foundation/presentation-exchange/)
* Use an [AuthorizationCredential](https://github.com/trustbloc/context/blob/master/vc/authorization-credential-v1.jsonld) to access remote credentials on behalf of the end-user

## Issuer Adapter

Issuer adapter acts on behalf of Issuer to perform DIDComm related use cases.

[Documentation](https://github.com/trustbloc/edge-adapter/blob/master/docs/issuer/README.md).

**Comment by rolsonquadras** [comment]
Issuer Adapter interacts with Wallet and RP Adapter to share the user data from the Issuer through [CHAPI](https://w3c-ccg.github.io/credential-handler-api/) and [DIDComm](https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0005-didcomm) protocols.

- [Sequence Diagram](https://github.com/trustbloc/edge-adapter/tree/master/docs/issuer#sequence-diagram)
- Components
  - [Wallet](https://github.com/trustbloc/edge-adapter/blob/master/docs/issuer/wallet_integration.md) 
    - Connects through CHAPI and DIDComm to share the Authorization credentials for the user data.
  - [RP Adapter](https://github.com/trustbloc/edge-adapter/blob/master/docs/issuer/rp_adapter_integration.md)
    - Connects through DIDComm to get the actual user data from Authorization credentials shared by the wallet. 
  - [Issuer](https://github.com/trustbloc/edge-adapter/blob/master/docs/issuer/issuer_integration.md)
    - Connects through HTTP APIs to get the User data.

Refer [this](https://github.com/trustbloc/edge-adapter/blob/master/docs/issuer/README.md) for complete documentation.

**Comment by llorllale** [comment]
Release notes are live: https://github.com/trustbloc/edge-adapter/releases/tag/v0.1.4
